from datetime import datetime
from pydantic import BaseModel, PositiveInt, Field

class ContratoLayoutDDGS(BaseModel):
    """
    Classe responsável pelo contrato do arquivo de DDGS.

    """
    cod_rotina: PositiveInt = Field(alias='Cód. Rotina')
    rotina: str = Field(alias='Rotina')
    status_pedido: str = Field(alias='Status Pedido')
    produto: str = Field(alias='Produto')
    mercado: str = Field(alias='Mercado')
    gef: str = Field(alias='GEF')
    nome_supervisor: str = Field(alias='Nome Supervisor')
    cod_cliente: int = Field(alias='Cód. Cliente')
    nome: str = Field(alias='Nome')
    data_pedido: datetime = Field(alias='Data Pedido', format='%d/%m/%Y %H:%M')
    inicio_cadencia: datetime = Field(alias='Início Cadência', format='%d/%m/%Y %H:%M')
    fim_cadencia: datetime = Field(alias='Fim Cadência', format='%d/%m/%Y %H:%M')
    pedido: int = Field(alias='Pedido')
    vol_total_vendido: float = Field(alias='Vol. Total Vendido')
    vol_total_carregado: float = Field(alias='Vol. Total Carregado')
    vol_total_pendente: float = Field(alias='Vol. Total Pendente')
    forecast_total: float = Field(alias='Forecast Total')
    #nao_cadenciado: int = Field(alias='Não Cadenciado')
    forecast_jan_2024: float = Field(alias='Forecast jan/2024')
    carregado_jan_2024: float = Field(alias='Carregado jan/2024')
    forecast_fev_2024: float = Field(alias='Forecast fev/2024')
    carregado_fev_2024: float = Field(alias='Carregado fev/2024')
    forecast_mar_2024: float = Field(alias='Forecast mar/24')
    carregado_mar_2024: float = Field(alias='Carregado mar/2024')
    forecast_abr_2024: float = Field(alias='Forecast abr/24')
    carregado_abr_2024: float = Field(alias='Carregado abr/2024')
    forecast_mai_2024: float = Field(alias='Forecast mai/24')
    carregado_mai_2024: float = Field(alias='Carregado mai/2024')
    forecast_jun_2024: float = Field(alias='Forecast jun/24')
    carregado_jun_2024: float = Field(alias='Carregado jun/2024')
    forecast_jul_2024: float = Field(alias='Forecast jul/24')
    carregado_jul_2024: float = Field(alias='Carregado jul/2024')
    forecast_ago_2024: float = Field(alias='Forecast ago/24')
    carregado_ago_2024: float = Field(alias='Carregado ago/2024')
    forecast_set_2024: float = Field(alias='Forecast set/2024')
    carregado_set_2024: float = Field(alias='Carregado set/2024')
    forecast_out_2024: float = Field(alias='Forecast out/2024')
    carregado_out_2024: float = Field(alias='Carregado out/2024')
    forecast_nov_2024: float = Field(alias='Forecast nov/2024')
    carregado_nov_2024: float = Field(alias='Carregado nov/2024')
    forecast_dez_2024: float = Field(alias='Forecast dez/2024')
    carregado_dez_2024: float = Field(alias='Carregado dez/2024')
